name = "CompressedBeliefMDPs"
uuid = "0a809e47-b8eb-4578-b4e8-4c2c5f9f833c"
authors = ["Logan-Mondal-Bhamidipaty"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
